### ISSUE TITLE
Add module-info.java?

### ISSUE THREAD

**Issue by ice1000** [sourcebuddy/sourcebuddy#7]
Can we have module-info.java in the release? Currently, when I try to import source buddy in my project (code is simplified):

```java
module rua {
  requires SourceBuddy;
}
```

It gives me the following error:

```
¿\src\main\java\module-info.java:12: error: module not found: SourceBuddy
  requires SourceBuddy;
           ^
```

**Comment by verhas** [comment]
I should have made it a module from the beginning. I will take a look.

**Comment by verhas** [comment]
I created the release 2.5.2, which should address this issue. It is available from Maven Central.

The module name is not `SourceBuddy`, as opposed to what your comment implicitly suggested. That is not compliant with the usual namings. It is `com.javax0.sourcebuddy`, which is still not fully compliant with the conventions because of the trailing digit, but ... okay. 

It was a great idea to make it modular, and I was happy to make it happen.

**Comment by ice1000** [comment]
Thank you!

The module name was generated by IntelliJ IDEA autocompletion.
